
=== RUNNING rnn =============

0
training for language fi
Model loaded from ../checkpoints/bpe/bpe_model_fi_1000.pkl
Epoch 1/2
  0%|          | 0/9 [00:00<?, ?it/s]  0%|          | 0/9 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/hlp179/nlp/aske/lstm/runscripts/run_lstm.py", line 50, in <module>
    train_loss = train(model, train_loader, criterion, optimizer, device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hlp179/nlp/aske/lstm/runscripts/../model/lstm.py", line 25, in train
    for batch in tqdm(data_loader):
  File "/opt/software/anaconda3/2024.06-py3.12.4/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/hlp179/.local/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/hlp179/.local/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hlp179/.local/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/hlp179/nlp/aske/lstm/runscripts/../utils/dataset.py", line 16, in __getitem__
    question = self.data[idx]['translated'] 
               ~~~~~~~~~^^^^^
KeyError: 2
... done <3
